name: GetBlocks
main: net.jandie1505.getblocks.GetBlocks
version: 1.0
api-version: 1.13
commands:
  getblocks:
    description: "export blocks to json file"
    usage: "/getblocks <world> <x1> <y1> <z1> <x2> <y2> <z2> <filename> <format>"
    permission: getblocks.use
permissions:
  getblocks.use:
    description: "Use the plugin"
    default: op
  getblocks.*:
    description: "wildcard permission"
    children:
      - getblocks.use
    default: op
author: jandie1505
website: jandie1505.net
